DROP TABLE COMISION_VENTAS;
DROP TABLE VENTAS;
DROP TABLE EMPLEADO;
DROP TABLE TIPO_EMPLEADO;


CREATE TABLE TIPO_EMPLEADO(
    TIPO_EMPLEADO       NUMBER(2) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1
    MAXVALUE 99999
    START WITH 1
    INCREMENT BY 1,
    DESC_TIPO_EMPLEADO  VARCHAR(25) NOT NULL,
    CONSTRAINT  PK_TIPO_EMPLEADO PRIMARY KEY (TIPO_EMPLEADO)
    );

--SE INSERTA TIPO EMPLEADO SIN ID YA QUE SE GENERA AUTOMATICAMENTE
INSERT INTO TIPO_EMPLEADO (DESC_TIPO_EMPLEADO)
VALUES ('EL MEJOR EMPLEADO');


CREATE TABLE EMPLEADO
(
    ID_EMPLEADO     NUMBER  (5) GENERATED ALWAYS AS IDENTITY
	MINVALUE 1
	MAXVALUE 999999
	START WITH 2
	INCREMENT BY 2,
    NUMRUT          NUMBER(10)   NOT NULL,
    DVRUT           VARCHAR2(1)  NOT NULL,
    PRIMER_NOMBRE   VARCHAR (20) NOT NULL,
	SNOMBRE         VARCHAR2(20) NOT NULL,
    APPATERNO       VARCHAR2(20) NOT NULL,
	APMATERNO       VARCHAR2(20) NOT NULL,
    FECHA_CONTRATO  DATE NOT NULL,
    TIPO_EMPLEADO   NUMBER(2) NOT NULL,
    CONSTRAINT  PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO)
);

--SE ALTERA TABLA AGREGANDO LA FK DE TIPO EMPLEADO
ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO FOREIGN KEY (TIPO_EMPLEADO)
REFERENCES TIPO_EMPLEADO (TIPO_EMPLEADO);

--POSTERIOR A LA CREACION DE TIPO EMPLEADO Y EMPLEADO CON SU FK SE DEBE AGREGAR DATOS YA QUE NO SE PUEDE GENERAR UN EMPLEADO SI NO EXISTE UN TIPO EMPLEADO
INSERT INTO EMPLEADO (NUMRUT, DVRUT, PRIMER_NOMBRE, SNOMBRE, APPATERNO, APMATERNO, FECHA_CONTRATO, TIPO_EMPLEADO) 
VALUES (18097282, 'K', 'RODRIGO', 'JAVIER', 'TRANOLAO', 'ZAMBRANO', TO_DATE('2023-06-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);

INSERT INTO EMPLEADO (NUMRUT, DVRUT, PRIMER_NOMBRE, SNOMBRE, APPATERNO, APMATERNO, FECHA_CONTRATO, TIPO_EMPLEADO) 
VALUES (9980538, '2', 'OLIVIA', 'DEL CARMEN', 'ZAMBRANO', 'TORRES', TO_DATE('2023-06-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);

CREATE TABLE VENTAS (
    NRO_BOLETA      NUMBER(8) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1
    MAXVALUE 99999
    START WITH 4
    INCREMENT BY 4,
    ID_EMPLEADO     NUMBER(5) NOT NULL,
    FECHA_BOLETA    DATE NOT NULL,
    MONTO_TOTAL     NUMBER(8) NOT NULL,
    CONSTRAINT  PK_VENTAS PRIMARY KEY (NRO_BOLETA));

--SE ALTERA TABLA PARA GENERAR FK DE EMPLEADO
ALTER TABLE VENTAS
ADD CONSTRAINT FK_VENTAS FOREIGN KEY (ID_EMPLEADO)
REFERENCES EMPLEADO (ID_EMPLEADO);

CREATE TABLE COMISION_VENTAS (
    NRO_BOLETA      NUMBER(8) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1
    MAXVALUE 99999
    START WITH 4
    INCREMENT BY 4,
    MONTO_COMISION     NUMBER(8) NOT NULL,
    CONSTRAINT  PK_COMISION_VENTAS PRIMARY KEY (NRO_BOLETA)
    );

--SE ALTERA TABLA PARA AGREGAR FK DE VENTAS Y TENGA DEPENDENCIA
ALTER TABLE COMISION_VENTAS
ADD CONSTRAINT FK_COMISION_VENTAS FOREIGN KEY (NRO_BOLETA)
REFERENCES VENTAS (NRO_BOLETA);

--POSTERIOR A LA CREACION DE COMISION VENTAS Y VENTAS CON SU FK, SE PUEDE AGREGAR DATOS DADO QUE DEPENDEN ENTRE SI
INSERT INTO VENTAS (ID_EMPLEADO, FECHA_BOLETA, MONTO_TOTAL)
VALUES (2, TO_DATE('2023-06-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10666);

INSERT INTO VENTAS (ID_EMPLEADO, FECHA_BOLETA, MONTO_TOTAL)
VALUES (4, TO_DATE('2023-06-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 666);

INSERT INTO COMISION_VENTAS (MONTO_COMISION)
VALUES (1000);

INSERT INTO COMISION_VENTAS (MONTO_COMISION)
VALUES (1000);


SELECT * FROM EMPLEADO;
SELECT * FROM TIPO_EMPLEADO;
SELECT * FROM VENTAS;
SELECT * FROM COMISION_VENTAS;
